export {
  archiveProduct,
  createProduct,
  emptyProductInput,
  fetchAdminProducts,
  fetchCatalogConfig,
  fetchProducts,
  fileToImageUpload,
  formatProductPrice,
  getAppsScriptUrl,
  getMockAdminPassword,
  isCatalogApiConfigured,
  loginAdmin,
  productToInput,
  updateProduct,
  useMockCatalog,
} from "@/api/catalogClient";
