/**
 * Print with Zwe — Catalog API (Google Apps Script)
 *
 * Deploy as Web app (Execute as: Me, Who has access: Anyone).
 * Run setupWorkspace() once after setting Script Properties.
 *
 * Script Properties (minimum):
 *   ADMIN_EMAIL, ADMIN_PASSWORD
 * Optional:
 *   DRIVE_ROOT_FOLDER_ID (defaults to Print with Zwe gallery folder)
 *   ADMIN_API_SECRET (auto-generated by setupWorkspace if missing)
 *
 * After setupWorkspace(), these are written automatically:
 *   SPREADSHEET_ID, PRODUCTS_FOLDER_ID, TRASH_FOLDER_ID
 */

var DEFAULT_DRIVE_ROOT = "1A65jclkdLnyAhN1J1kAXcArXsJe7FnBu";
var SESSION_HOURS = 24;
var PRODUCT_HEADERS = [
  "id",
  "title",
  "description",
  "price",
  "currency",
  "material",
  "category",
  "inStock",
  "featured",
  "archived",
  "imageUrls",
  "folderId",
  "createdAt",
  "updatedAt",
];

function doGet(e) {
  try {
    var action = (e && e.parameter && e.parameter.action) || "";
    var params = e && e.parameter ? e.parameter : {};

    switch (action) {
      case "getConfig":
        return jsonOk(getConfig());
      case "listProducts":
        return jsonOk({ items: listProducts(false) });
      case "getProduct":
        if (!params.id) return jsonError("Missing id");
        return jsonOk({ item: getProduct(params.id) });
      case "adminListProducts":
        requireAuth(params.token);
        return jsonOk({ items: listProducts(true) });
      default:
        return jsonError("Unknown action: " + action);
    }
  } catch (err) {
    return jsonError(err.message || String(err));
  }
}

function doPost(e) {
  try {
    var body = parseBody(e);
    var action = body.action || (e.parameter && e.parameter.action) || "";

    switch (action) {
      case "login":
        return jsonOk(login(body.email, body.password));
      case "createProduct":
        requireAuth(body.token);
        return jsonOk({ item: createProduct(body) });
      case "updateProduct":
        requireAuth(body.token);
        if (!body.id) return jsonError("Missing id");
        return jsonOk({ item: updateProduct(body.id, body) });
      case "deleteProduct":
        requireAuth(body.token);
        if (!body.id) return jsonError("Missing id");
        deleteProduct(body.id);
        return jsonOk({ ok: true });
      default:
        return jsonError("Unknown action: " + action);
    }
  } catch (err) {
    return jsonError(err.message || String(err));
  }
}

// ── Setup ────────────────────────────────────────────────────────────────

function setupWorkspace() {
  ensureSecret();

  var rootId = getProp("DRIVE_ROOT_FOLDER_ID") || DEFAULT_DRIVE_ROOT;
  var root = DriveApp.getFolderById(rootId);

  var spreadsheet = SpreadsheetApp.create("Print with Zwe Catalog");
  var sheet = spreadsheet.getActiveSheet();
  sheet.setName("Products");
  sheet.getRange(1, 1, 1, PRODUCT_HEADERS.length).setValues([PRODUCT_HEADERS]);

  var configSheet = spreadsheet.insertSheet("Config");
  configSheet.getRange(1, 1, 1, 2).setValues([["key", "value"]]);
  configSheet.getRange(2, 1, 6, 2).setValues([
    ["SITE_NAME", "Print with Zwe"],
    ["CURRENCY_CODE", "MMK"],
    ["CATEGORIES", "Functional,Desk,Gifts,Custom"],
    ["TELEGRAM_USERNAME", "zwe_ll"],
    ["PHONE_NUMBER", "+959787238201"],
    ["SHOP_TITLE", "Shop Catalog"],
  ]);

  moveFileToFolder(spreadsheet.getId(), root);

  var productsFolder = getOrCreateSubfolder(root, "products");
  var trashFolder = getOrCreateSubfolder(root, "_trash");

  setProp("SPREADSHEET_ID", spreadsheet.getId());
  setProp("PRODUCTS_FOLDER_ID", productsFolder.getId());
  setProp("TRASH_FOLDER_ID", trashFolder.getId());
  setProp("DRIVE_ROOT_FOLDER_ID", rootId);

  Logger.log("Setup complete");
  Logger.log("SPREADSHEET_ID=" + spreadsheet.getId());
  Logger.log("PRODUCTS_FOLDER_ID=" + productsFolder.getId());
  Logger.log("TRASH_FOLDER_ID=" + trashFolder.getId());
  Logger.log("DRIVE_ROOT_FOLDER_ID=" + rootId);
}

/** Run from the Apps Script editor to confirm Drive write access. */
function verifyDriveAccess() {
  var productsFolderId = getProp("PRODUCTS_FOLDER_ID");
  if (!productsFolderId) {
    throw new Error("PRODUCTS_FOLDER_ID missing. Run setupWorkspace() first.");
  }

  var testId = driveUploadFile(
    "access-test.txt",
    "text/plain",
    productsFolderId,
    Utilities.newBlob("Print with Zwe Drive test").getBytes(),
  );
  driveMakePublic(testId);
  Logger.log("Drive write OK. Test file id: " + testId);
  driveTrashFile(testId);
  Logger.log("Test file deleted. Your catalog can upload photos.");
}

// ── Config ───────────────────────────────────────────────────────────────

function getConfig() {
  var config = {
    siteName: "Print with Zwe",
    currencyCode: "MMK",
    categories: ["Functional", "Desk", "Gifts", "Custom"],
    telegramUsername: "zwe_ll",
    phoneNumber: "+959787238201",
    shopTitle: "Shop Catalog",
  };

  var sheetConfig = readConfigSheet();
  if (sheetConfig.SITE_NAME) config.siteName = sheetConfig.SITE_NAME;
  if (sheetConfig.CURRENCY_CODE) config.currencyCode = sheetConfig.CURRENCY_CODE;
  if (sheetConfig.CATEGORIES) {
    config.categories = sheetConfig.CATEGORIES.split(",").map(trim).filter(Boolean);
  }
  if (sheetConfig.TELEGRAM_USERNAME) config.telegramUsername = sheetConfig.TELEGRAM_USERNAME;
  if (sheetConfig.PHONE_NUMBER) config.phoneNumber = sheetConfig.PHONE_NUMBER;
  if (sheetConfig.SHOP_TITLE) config.shopTitle = sheetConfig.SHOP_TITLE;

  return config;
}

function readConfigSheet() {
  var sheet = getConfigSheet();
  if (!sheet) return {};

  var values = sheet.getDataRange().getValues();
  var map = {};
  for (var i = 1; i < values.length; i++) {
    var key = trim(String(values[i][0] || ""));
    if (!key) continue;
    map[key] = trim(String(values[i][1] || ""));
  }
  return map;
}

// ── Auth ─────────────────────────────────────────────────────────────────

function login(email, password) {
  var expectedEmail = getProp("ADMIN_EMAIL");
  var expectedPassword = getProp("ADMIN_PASSWORD");

  if (!expectedEmail || !expectedPassword) {
    throw new Error("Admin credentials not configured in Script Properties");
  }

  if (trim(email).toLowerCase() !== trim(expectedEmail).toLowerCase()) {
    throw new Error("Invalid email or password");
  }
  if (String(password) !== String(expectedPassword)) {
    throw new Error("Invalid email or password");
  }

  return { token: createSessionToken(email), email: expectedEmail };
}

function requireAuth(token) {
  if (!validateSessionToken(token)) {
    throw new Error("Unauthorized");
  }
}

function createSessionToken(email) {
  ensureSecret();
  var secret = getProp("ADMIN_API_SECRET");
  var expiresAt = Date.now() + SESSION_HOURS * 60 * 60 * 1000;
  var payload = email + "|" + expiresAt;
  var sigBytes = Utilities.computeHmacSha256Signature(payload, secret);
  var sig = Utilities.base64EncodeWebSafe(sigBytes);
  return Utilities.base64EncodeWebSafe(payload + "|" + sig);
}

function validateSessionToken(token) {
  if (!token) return false;
  ensureSecret();
  var secret = getProp("ADMIN_API_SECRET");

  try {
    var decoded = Utilities.newBlob(Utilities.base64DecodeWebSafe(token)).getDataAsString();
    var parts = decoded.split("|");
    if (parts.length !== 3) return false;

    var email = parts[0];
    var expiresAt = Number(parts[1]);
    var sig = parts[2];
    var payload = email + "|" + expiresAt;
    var expectedSig = Utilities.base64EncodeWebSafe(
      Utilities.computeHmacSha256Signature(payload, secret),
    );

    if (sig !== expectedSig) return false;
    if (Date.now() > expiresAt) return false;

    var adminEmail = getProp("ADMIN_EMAIL");
    return trim(email).toLowerCase() === trim(adminEmail).toLowerCase();
  } catch (e) {
    return false;
  }
}

// ── Products ─────────────────────────────────────────────────────────────

function listProducts(includeArchived) {
  var sheet = getProductsSheet();
  var values = sheet.getDataRange().getValues();
  var items = [];

  for (var i = 1; i < values.length; i++) {
    var row = rowToProduct(values[i]);
    if (!row) continue;
    if (!includeArchived && row.archived) continue;
    items.push(row);
  }

  items.sort(function (a, b) {
    return String(b.updatedAt).localeCompare(String(a.updatedAt));
  });

  return items;
}

function getProduct(id) {
  var row = findProductRow(id);
  if (!row) throw new Error("Product not found");
  return row.product;
}

function createProduct(body) {
  var sheet = getProductsSheet();
  var id = "prod_" + Utilities.getUuid().replace(/-/g, "").slice(0, 12);
  var now = new Date().toISOString();
  var folderId = createProductFolder(id, body.title || id);
  var imageUrls = saveImages(folderId, body.images || []);
  if (body.imageUrls && body.imageUrls.length) {
    imageUrls = imageUrls.concat(body.imageUrls);
  }

  var product = {
    id: id,
    title: trim(body.title),
    description: trim(body.description),
    price: Number(body.price) || 0,
    currency: trim(body.currency || getConfig().currencyCode || "MMK"),
    material: trim(body.material || "PLA"),
    category: trim(body.category || "Custom"),
    inStock: body.inStock !== false,
    featured: body.featured === true,
    archived: false,
    imageUrls: uniqueUrls(imageUrls),
    folderId: folderId,
    createdAt: now,
    updatedAt: now,
  };

  if (!product.title) throw new Error("Title is required");
  if (!product.imageUrls.length) throw new Error("At least one image is required");

  sheet.appendRow(productToRow(product));
  return product;
}

function updateProduct(id, body) {
  var found = findProductRow(id);
  if (!found) throw new Error("Product not found");

  var existing = found.product;
  var folderId = existing.folderId
    ? existing.folderId
    : createProductFolder(id, body.title || existing.title);

  var imageUrls = Array.isArray(body.imageUrls)
    ? body.imageUrls.slice()
    : existing.imageUrls.slice();

  if (body.images && body.images.length) {
    imageUrls = imageUrls.concat(saveImages(folderId, body.images));
  }

  var product = {
    id: existing.id,
    title: trim(body.title !== undefined ? body.title : existing.title),
    description: trim(
      body.description !== undefined ? body.description : existing.description,
    ),
    price: Number(body.price !== undefined ? body.price : existing.price) || 0,
    currency: trim(
      body.currency !== undefined ? body.currency : existing.currency,
    ),
    material: trim(body.material !== undefined ? body.material : existing.material),
    category: trim(body.category !== undefined ? body.category : existing.category),
    inStock:
      body.inStock !== undefined ? body.inStock !== false : existing.inStock,
    featured:
      body.featured !== undefined ? body.featured === true : existing.featured,
    archived:
      body.archived !== undefined ? body.archived === true : existing.archived,
    imageUrls: uniqueUrls(imageUrls),
    folderId: folderId,
    createdAt: existing.createdAt,
    updatedAt: new Date().toISOString(),
  };

  if (!product.title) throw new Error("Title is required");
  if (!product.imageUrls.length) throw new Error("At least one image is required");

  var rowValues = productToRow(product);
  sheetWriteRow(found.sheet, found.rowIndex, rowValues);
  return product;
}

function deleteProduct(id) {
  var found = findProductRow(id);
  if (!found) throw new Error("Product not found");

  var product = found.product;
  product.archived = true;
  product.updatedAt = new Date().toISOString();

  if (product.folderId) {
    try {
      moveFolderToTrash(product.folderId);
    } catch (e) {
      // Folder may already be moved.
    }
  }

  sheetWriteRow(found.sheet, found.rowIndex, productToRow(product));
}

// ── Drive helpers (Drive API v3 — works in web app POST requests) ────────

function driveAuthHeaders() {
  return { Authorization: "Bearer " + ScriptApp.getOAuthToken() };
}

function driveApiError(response, fallback) {
  try {
    var data = JSON.parse(response.getContentText());
    if (data && data.error && data.error.message) return data.error.message;
  } catch (e) {
    // ignore parse errors
  }
  return fallback + " (HTTP " + response.getResponseCode() + ")";
}

function createProductFolder(id, title) {
  var productsFolderId = getProp("PRODUCTS_FOLDER_ID");
  if (!productsFolderId) {
    throw new Error("Catalog not set up. Run setupWorkspace() in Apps Script first.");
  }

  var safeName = slugify(title || id) + " [" + id + "]";
  return driveCreateFolder(safeName, productsFolderId);
}

function saveImages(folderId, images) {
  var urls = [];
  if (!images || !images.length) return urls;

  for (var i = 0; i < images.length; i++) {
    var image = images[i];
    if (!image || !image.data) continue;
    var name = image.name || "image-" + (i + 1) + ".jpg";
    var mime = image.mimeType || "image/jpeg";
    var bytes = Utilities.base64Decode(image.data);
    var fileId = driveUploadFile(name, mime, folderId, bytes);
    driveMakePublic(fileId);
    urls.push(driveImageUrl(fileId));
  }

  return urls;
}

function moveFolderToTrash(folderId) {
  var trashFolderId = getProp("TRASH_FOLDER_ID");
  if (!trashFolderId) return;
  driveMoveFile(folderId, trashFolderId);
}

function driveCreateFolder(name, parentId) {
  var response = UrlFetchApp.fetch("https://www.googleapis.com/drive/v3/files", {
    method: "post",
    contentType: "application/json",
    headers: driveAuthHeaders(),
    payload: JSON.stringify({
      name: name,
      mimeType: "application/vnd.google-apps.folder",
      parents: [parentId],
    }),
    muteHttpExceptions: true,
  });

  if (response.getResponseCode() >= 300) {
    throw new Error(driveApiError(response, "Could not create product folder"));
  }

  return JSON.parse(response.getContentText()).id;
}

function driveUploadFile(name, mimeType, parentId, bytes) {
  var boundary = "pwz_" + Utilities.getUuid();
  var metadata = JSON.stringify({ name: name, parents: [parentId] });
  var payload =
    "--" +
    boundary +
    "\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n" +
    metadata +
    "\r\n--" +
    boundary +
    "\r\nContent-Type: " +
    mimeType +
    "\r\nContent-Transfer-Encoding: base64\r\n\r\n" +
    Utilities.base64Encode(bytes) +
    "\r\n--" +
    boundary +
    "--";

  var response = UrlFetchApp.fetch(
    "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart",
    {
      method: "post",
      contentType: 'multipart/related; boundary="' + boundary + '"',
      headers: driveAuthHeaders(),
      payload: payload,
      muteHttpExceptions: true,
    },
  );

  if (response.getResponseCode() >= 300) {
    throw new Error(driveApiError(response, "Could not upload image to Drive"));
  }

  return JSON.parse(response.getContentText()).id;
}

function driveMakePublic(fileId) {
  UrlFetchApp.fetch(
    "https://www.googleapis.com/drive/v3/files/" + fileId + "/permissions",
    {
      method: "post",
      contentType: "application/json",
      headers: driveAuthHeaders(),
      payload: JSON.stringify({ role: "reader", type: "anyone" }),
      muteHttpExceptions: true,
    },
  );
}

function driveMoveFile(fileId, newParentId) {
  var infoResponse = UrlFetchApp.fetch(
    "https://www.googleapis.com/drive/v3/files/" +
      fileId +
      "?fields=parents&supportsAllDrives=true",
    {
      headers: driveAuthHeaders(),
      muteHttpExceptions: true,
    },
  );

  if (infoResponse.getResponseCode() >= 300) return;

  var info = JSON.parse(infoResponse.getContentText());
  var parents = info.parents || [];
  if (!parents.length) return;

  UrlFetchApp.fetch(
    "https://www.googleapis.com/drive/v3/files/" +
      fileId +
      "?addParents=" +
      encodeURIComponent(newParentId) +
      "&removeParents=" +
      encodeURIComponent(parents.join(",")) +
      "&supportsAllDrives=true",
    {
      method: "patch",
      headers: driveAuthHeaders(),
      muteHttpExceptions: true,
    },
  );
}

function driveTrashFile(fileId) {
  UrlFetchApp.fetch(
    "https://www.googleapis.com/drive/v3/files/" + fileId + "?supportsAllDrives=true",
    {
      method: "patch",
      contentType: "application/json",
      headers: driveAuthHeaders(),
      payload: JSON.stringify({ trashed: true }),
      muteHttpExceptions: true,
    },
  );
}

function driveImageUrl(fileId) {
  return "https://drive.google.com/thumbnail?id=" + fileId + "&sz=w1200";
}

// ── Sheet helpers ────────────────────────────────────────────────────────

function getProductsSheet() {
  var id = getProp("SPREADSHEET_ID");
  if (!id) throw new Error("Catalog not set up. Run setupWorkspace() first.");
  var sheet = SpreadsheetApp.openById(id).getSheetByName("Products");
  if (!sheet) throw new Error("Products sheet not found");
  return sheet;
}

function getConfigSheet() {
  var id = getProp("SPREADSHEET_ID");
  if (!id) return null;
  return SpreadsheetApp.openById(id).getSheetByName("Config");
}

function findProductRow(id) {
  var sheet = getProductsSheet();
  var values = sheet.getDataRange().getValues();

  for (var i = 1; i < values.length; i++) {
    if (String(values[i][0]) === String(id)) {
      return {
        sheet: sheet,
        rowIndex: i + 1,
        product: rowToProduct(values[i]),
      };
    }
  }
  return null;
}

function sheetWriteRow(sheet, rowIndex, values) {
  // getRange(row, column, numRows, numColumns) — third arg is row COUNT, not end row
  sheet.getRange(rowIndex, 1, 1, values.length).setValues([values]);
}

function rowToProduct(row) {
  if (!row || !row[0]) return null;

  var imageUrls = [];
  try {
    imageUrls = JSON.parse(String(row[10] || "[]"));
    if (!Array.isArray(imageUrls)) imageUrls = [];
  } catch (e) {
    imageUrls = [];
  }

  var product = {
    id: String(row[0]),
    title: String(row[1] || ""),
    description: String(row[2] || ""),
    price: Number(row[3]) || 0,
    currency: String(row[4] || "MMK"),
    material: String(row[5] || "PLA"),
    category: String(row[6] || "Custom"),
    inStock: String(row[7]).toUpperCase() !== "FALSE",
    featured: String(row[8]).toUpperCase() === "TRUE",
    archived: String(row[9]).toUpperCase() === "TRUE",
    imageUrls: imageUrls,
    folderId: String(row[11] || ""),
    createdAt: String(row[12] || ""),
    updatedAt: String(row[13] || ""),
  };

  product.imageUrl = product.imageUrls[0] || "";
  return product;
}

function productToRow(product) {
  return [
    product.id,
    product.title,
    product.description,
    product.price,
    product.currency,
    product.material,
    product.category,
    product.inStock ? "TRUE" : "FALSE",
    product.featured ? "TRUE" : "FALSE",
    product.archived ? "TRUE" : "FALSE",
    JSON.stringify(product.imageUrls || []),
    product.folderId || "",
    product.createdAt,
    product.updatedAt,
  ];
}

// ── Utilities ────────────────────────────────────────────────────────────

function parseBody(e) {
  if (!e || !e.postData || !e.postData.contents) return {};
  return JSON.parse(e.postData.contents);
}

function jsonOk(data) {
  var payload = { ok: true };
  for (var key in data) {
    if (Object.prototype.hasOwnProperty.call(data, key)) {
      payload[key] = data[key];
    }
  }
  return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(
    ContentService.MimeType.JSON,
  );
}

function jsonError(message) {
  return ContentService.createTextOutput(
    JSON.stringify({ ok: false, error: message }),
  ).setMimeType(ContentService.MimeType.JSON);
}

function getProp(key) {
  return PropertiesService.getScriptProperties().getProperty(key);
}

function setProp(key, value) {
  PropertiesService.getScriptProperties().setProperty(key, String(value));
}

function ensureSecret() {
  if (!getProp("ADMIN_API_SECRET")) {
    setProp("ADMIN_API_SECRET", Utilities.getUuid() + Utilities.getUuid());
  }
}

function trim(value) {
  return String(value || "").trim();
}

function slugify(value) {
  return trim(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48) || "product";
}

function uniqueUrls(urls) {
  var seen = {};
  var result = [];
  for (var i = 0; i < urls.length; i++) {
    var url = trim(urls[i]);
    if (!url || seen[url]) continue;
    seen[url] = true;
    result.push(url);
  }
  return result;
}

function getOrCreateSubfolder(parentFolder, name) {
  var folders = parentFolder.getFoldersByName(name);
  if (folders.hasNext()) return folders.next();
  return parentFolder.createFolder(name);
}

function moveFileToFolder(fileId, folder) {
  var file = DriveApp.getFileById(fileId);
  folder.addFile(file);
  DriveApp.getRootFolder().removeFile(file);
}
